### ISSUE TITLE
issue with opening a movie from yes movies 

### ISSUE THREAD

**Issue by dreadwng** [engMaher/LLG-MP#1]
when i try to click anywhere to open a movie from yesmovies tab in the media player menu it gives me this error 

<img src="https://imgbbb.com/images/2019/05/02/issue.png" alt="issue.png" border="0" />

**Comment by engMaher** [comment]
solved in the latest [release 0.1.1](https://github.com/engMaher/LLG-MP/releases/tag/0.1.1) .
 For future reference : the issue was caused by an electron bug , it produces that error when ads/popups try to open new electron windows prior to setting their id , reversing this electron buggy [pull request ](https://github.com/electron/electron/commit/a2b3cf95a747c331cabb0dd1f1e3ad93be6b3120?diff=split)solved the issue
